### ISSUE TITLE
Is there a overlay hotkey?

### ISSUE THREAD

**Issue by poprox24** [mob41/osumer#40]
### My environment

- My operating system: Windows 10 64bit

- My Java Version: Java 8(latest from java.com)

### About my issue
Is there overlay button inside osu so I don't need to press alt tab to the program everytime?

**Comment by a1aw** [comment]
Hi, there aren't any overlay hotkey yet. The overlay is just a progress bar for monitoring the status of the multiplayer map you are downloading. It will be automatically shown and hidden when it is needed.

I cannot develop more for the overlay part because the mouse acceleration problem. I currently cannot find a way to modify the mouse acceleration.

**Comment by poprox24** [comment]
Oh, thanks.


Dne čt 7. 1. 2021 19:49 uživatel Anthony Law <notifications@github.com>
napsal:
