### ISSUE TITLE
Osu Updated the beatmap URL format to new site style

### ISSUE THREAD

**Issue by raven121875** [mob41/osumer#43]
### My environment

- My operating system: *OS Here*

- My Java Version: *Java version here*

**Comment by raven121875** [comment]
![image](https://user-images.githubusercontent.com/75301124/115860244-d3610300-a463-11eb-89f2-edc1d939e51e.png)

**Comment by a1aw** [comment]
Got it. Unfortunately, the new-site osu! beatmap parser hasn’t been implemented, and I am busy on other projects. osumer might be unusable for some weeks.

**Comment by a1aw** [comment]
@raven121875 I have tested right now with the classic No Title beatmap: https://osu.ppy.sh/s/320118 and there is no problem. The old-site beatmap parser is actually fetching the site at https:/old.ppy.sh/s/320118 instead of the above one. So as soon the old-site does not disappear, it will work as expected.

**Comment by raven121875** [comment]
It recognizes the beatmap when you put the link manually but it'll not download automatically when you download a map in multi. Sorry bad english haha

**Comment by raven121875** [comment]
https://osu.ppy.sh/beatmapsets/320118#osu/713818 I think this is the new format of beatmap link that's why osumer can't reognize it
